export interface Project { title: string; description: string; tech: string[]; github?: string; link?: string }
export interface Experience { title: string; company: string; period: string; points: string[] }
export const personalInfo = {
  name: "Sumit Mahajan", title: "Software Engineer II @ JPMorgan Chase", subtitle: "Quant Development | Systems Design | Distributed Systems",
  email: "ajaxx642022@gmail.com", github: "https://github.com/sumit-mahajan", linkedin: "https://linkedin.com/in/sumitmahajan", twitter: "https://x.com/sumitmahajan", location: "Mumbai, India",
  stats: [{value:"4+",label:"Years Experience"},{value:"32",label:"Migrations Led"},{value:"50K+",label:"Transactions/Day"}],
  skills: [{name:"Python",level:95},{name:"C# / .NET",level:90},{name:"TypeScript",level:85},{name:"React / Next.js",level:80},{name:"FastAPI",level:90},{name:"LangChain / LLM",level:85},{name:"AWS (Certified)",level:85},{name:"PostgreSQL",level:88},{name:"Docker / K8s",level:82},{name:"Kafka",level:80},{name:"Tailwind CSS",level:85},{name:"Git / CI/CD",level:90}],
  experience: [{title:"Software Engineer II",company:"JPMorgan Chase & Co.",period:"Oct 2022 \u2013 Present",points:["Architected real-time trade surveillance processing 50K+ daily transactions using Python, FastAPI, and Kafka","Led migration of 32 legacy .NET microservices to Python/TypeScript","Designed event-driven architecture managing $2B+ daily trade flows","Reduced incident response time by 60% through distributed tracing","Built LLM-powered compliance tools, cutting manual review by 40%","Mentored 6 junior engineers across 3 squads","Optimized Postgres queries for 100ms p99 latency at 10K+ QPS","Won internal hackathon for AI-driven anomaly detection prototype"]},{title:"Software Engineer I",company:"JPMorgan Chase & Co.",period:"Sep 2021 \u2013 Oct 2022",points:["Developed real-time data pipelines for market risk analytics","Built monitoring dashboards reducing alert noise by 50%","Collaborated on cross-functional quant dev initiatives"]}],
  projects: [{title:"Trade Surveillance Engine",description:"Real-time engine processing 50K+ daily transactions with ML-based anomaly detection",tech:["Python","FastAPI","Kafka","PostgreSQL","Docker"]},{title:"LLM Compliance Assistant",description:"AI-powered tool reducing manual compliance review by 40% using LLMs",tech:["LangChain","OpenAI","FastAPI","React"]},{title:"QAI - Quant Interview Prep",description:"AI platform for quant interview prep with adaptive learning paths",tech:["Next.js","Python","OpenAI","PostgreSQL"],link:"https://qai.dev"}],
  conferences: [{name:"AWS Community Day",organizer:"AWS User Group",year:2024,description:"Speaker - Building Scalable Data Pipelines"},{name:"JPMC Tech Summit",organizer:"JPMorgan Chase",year:2024,description:"Panelist - Modernizing Financial Infrastructure"},{name:"React India",organizer:"React India Community",year:2023,description:"Attendee & Workshop Facilitator"}],
  hobbies: ["Gym & Fitness","Guitar","Reading (Quant Finance, Sci-Fi)","Tech Writing","Gaming","Coffee Brewing"]
}